### ISSUE TITLE
Run fails on new system

### ISSUE THREAD

**Issue by rjhenry** [DanielWeeber/ansible-role-postfix_exporter#1]
Looks like the conditional `postfix_exporter_version_check.stdout is not defined` is never true; on a system with no such binary, I get the following value for `postfix_exporter_version_check`:
```
    "postfix_exporter_version_check": {
        "changed": false,
        "cmd": "/usr/local/bin/postfix_exporter --version",
        "failed": false,
        "failed_when_result": false,
        "msg": "[Errno 2] No such file or directory: b'/usr/local/bin/postfix_exporter'",
        "rc": 2,
        "stderr": "",
        "stderr_lines": [],
        "stdout": "",
        "stdout_lines": []
    }
```

On a host where this is installed, the `--version` flag doesn't appear to work anyway:
```
$ /usr/local/bin/postfix_exporter --version
postfix_exporter: error: unknown long flag '--version', try --help
```

Can be worked around by removing the conditional, but that then copies the binary every time the role is called.

**Comment by DanielWeeber** [comment]
I've applied a million of changes and bugfixes and also included automatic molecule testing.
Also this is now working for ubuntu and RedHat, including the molecule testing.

ref: https://github.com/DanielWeeber/ansible-role-postfix_exporter/commit/7e8ca78791fbd0e8e9f88305e19ff9caafd79652

Please update the role and try again :)

**Comment by DanielWeeber** [comment]
Regarding version flag I opened an issue https://github.com/kumina/postfix_exporter/issues/91

**Comment by rjhenry** [comment]
Cheers for your quick response, and apologies for the slow response on my part! Your changes look to have done the trick, many thanks. I hope there's a response for the upstream issue soon!

I'll close this one off - feel free to open an alternative to track the `version` implementation, or not, as the case may be!
